<?php

/**
 * Add the following markup to the page template where you want the output to appear
 */

/**
 * 
 * <?php if (variable_get('notification_bar_enabled')): ?>
 *   <?php if (variable_get('notification_bar_url')):?><a href="<?php print variable_get('notification_bar_url');?>"><?php endif; ?>
 *     <div class="statusbar" style="background-color: <?php print variable_get('notification_bar_color'); ?>; color: #FFFFFF; padding-top: 10px; padding-bottom: 10px; font-weight: bold; text-align: center; letter-spacing: .02em;">
 *       <div class="container" style="max-width: 1100px; margin-left: auto; margin-right: auto;">
 *         <?php print variable_get('notification_bar_message'); ?>
 *       </div>
 *     </div>
 *   <?php if (variable_get('notification_bar_url')):?></a><?php endif; ?>
 * <?php endif; ?>
 * 
 */

function notification_bar_menu() {
  $items['admin/config/system/notification_bar'] = array(
    'title' => 'Notification Bar',
    'description' => 'Configure notification bar.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('notification_bar_admin_settings_form'),
    'access arguments' => array('access content overview'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function notification_bar_admin_settings_form($form, &$form_state) {
  $form['notification_bar_enabled'] = [
    '#type' => 'checkbox',
    '#title' => 'Enabled',
    '#default_value' => variable_get('notification_bar_enabled', false)
  ];
  // $form['notification_bar_type'] = [
  //   '#type' => 'select',
  //   '#title' => 'Type',
  //   '#options' => [
  //     'urgent' => 'Urgent',
  //     'promotion' => 'Promotion'
  //   ],
  //   '#default_value' => variable_get('notification_bar_type', 'urgent')
  // ];
  $form['notification_bar_message'] = [
    '#type' => 'textarea',
    '#title' => 'Message',
    '#required' => true,
    '#default_value' => variable_get('notification_bar_message', '')
  ];
  $form['notification_bar_url'] = [
    '#type' => 'textfield',
    '#title' => 'URL',
    '#default_value' => variable_get('notification_bar_url', '')
  ];
  $form['notification_bar_button_text'] = [
    '#type' => 'textfield',
    '#title' => 'URL',
    '#default_value' => variable_get('notification_bar_button_text', '')
  ];

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save configuration'),
  );

  return $form;
}

function notification_bar_admin_settings_form_submit($form, &$form_state) {
  if ($form_state['values']['notification_bar_enabled']) {
    variable_set('notification_bar_enabled', 1);
  }
  else {
    variable_del('notification_bar_enabled');
  }
  // variable_set('notification_bar_type', $form_state['values']['notification_bar_type']);
  variable_set('notification_bar_message', $form_state['values']['notification_bar_message']);
  variable_set('notification_bar_url', $form_state['values']['notification_bar_url']);
  variable_set('notification_bar_button_text', $form_state['values']['notification_bar_button_text']);
  drupal_set_message(t('The notification bar settings have been saved.'));
}
