<?php

function notification_bar_menu() {
  $items['admin/config/system/notification_bar'] = array(
    'title' => 'Notification Bar',
    'description' => 'Configure notification bar.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('notification_bar_admin_settings_form'),
    'access arguments' => array('access content overview'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function notification_bar_admin_settings_form($form, &$form_state) {
  $form['notification_bar_enabled'] = [
    '#type' => 'checkbox',
    '#title' => 'Enabled',
    '#default_value' => variable_get('notification_bar_enabled', false)
  ];
  $form['notification_bar_color'] = [
    '#type' => 'select',
    '#title' => 'Color',
    '#options' => [
      '#000000' => 'Black',
      '#D10000' => 'Red',
      '#FF671F' => 'Orange',
      '#00AFD7' => 'Blue',
      '#C4D600' => 'Green'
    ],
    '#required' => true,
    '#default_value' => variable_get('notification_bar_color', '#000000')
  ];
  $form['notification_bar_message'] = [
    '#type' => 'textarea',
    '#title' => 'Message',
    '#required' => true,
    '#default_value' => variable_get('notification_bar_message', '')
  ];
  $form['notification_bar_url'] = [
    '#type' => 'textfield',
    '#title' => 'URL',
    '#default_value' => variable_get('notification_bar_url', '')
  ];

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save configuration'),
  );

  return $form;
}

function notification_bar_admin_settings_form_submit($form, &$form_state) {
  if ($form_state['values']['notification_bar_enabled']) {
    variable_set('notification_bar_enabled', 1);
  }
  else {
    variable_del('notification_bar_enabled');
  }

  variable_set('notification_bar_color', $form_state['values']['notification_bar_color']);
  variable_set('notification_bar_message', $form_state['values']['notification_bar_message']);
  variable_set('notification_bar_url', $form_state['values']['notification_bar_url']);
  
  drupal_set_message(t('The configuration options have been saved.'));
}
